stages:
  - deploy

before_script:
  - eval $(ssh-agent -s)
  - chmod 600 $SSH_PRIVATE_KEY
  - ssh-add $SSH_PRIVATE_KEY

deploy_staging:
  stage: deploy
  script:
    - ssh $USER@$APP_URL -o StrictHostKeyChecking=no ". ssh-restart.sh && ssh-add .ssh/convexityApps && cd token-chats && git fetch && git reset --hard origin/master && git pull origin master && docker-compose up --force-recreate --no-deps certbot && exit 0"
    # - ssh $USER@$APP_URL -o StrictHostKeyChecking=no ". ssh-restart.sh && ssh-add .ssh/convexityApps && cd token-chats && git fetch && git reset --hard origin/master && git pull origin master && docker-compose build token-app && docker-compose up -d && chmod +x ssl_renew.sh && exit"
  only:
    - master
